POLISH = {
    # Europa
    "Germany": "Niemcy",
    "Spain": "Hiszpania",
    "France": "Francja",
    "England": "Anglia",
    "Portugal": "Portugalia",
    "Netherlands": "Holandia",
    "Belgium": "Belgia",
    "Italy": "Włochy",
    "Switzerland": "Szwajcaria",
    "Croatia": "Chorwacja",
    "Denmark": "Dania",
    "Austria": "Austria",
    "Serbia": "Serbia",
    "Czech Republic": "Czechy",
    "Czechia": "Czechy",
    "Slovakia": "Słowacja",
    "Slovenia": "Słowenia",
    "Hungary": "Węgry",
    "Romania": "Rumunia",
    "Scotland": "Szkocja",
    "Turkey": "Turcja",
    "Türkiye": "Turcja",
    "Ukraine": "Ukraina",
    "Albania": "Albania",
    "Georgia": "Gruzja",
    "Poland": "Polska",
    "Greece": "Grecja",
    "Iceland": "Islandia",
    "Norway": "Norwegia",
    "Finland": "Finlandia",
    "Sweden": "Szwecja",
    "Wales": "Walia",
    "Bosnia and Herzegovina": "Bośnia i Hercegowina",
    "Montenegro": "Czarnogóra",
    "Kosovo": "Kosowo",
    "North Macedonia": "Macedonia Północna",
    "Bulgaria": "Bułgaria",
    "Ireland": "Irlandia",
    "Republic of Ireland": "Irlandia",
    "Northern Ireland": "Irlandia Północna",
    "Luxembourg": "Luksemburg",
    "Belarus": "Białoruś",
    "Lithuania": "Litwa",
    "Latvia": "Łotwa",
    "Estonia": "Estonia",
    "Moldova": "Mołdawia",
    "Armenia": "Armenia",
    "Azerbaijan": "Azerbejdżan",
    "Kazakhstan": "Kazachstan",
    "Gibraltar": "Gibraltar",
    "Malta": "Malta",
    "Cyprus": "Cypr",
    "Andorra": "Andora",
    "San Marino": "San Marino",
    "Liechtenstein": "Liechtenstein",
    "Faroe Islands": "Wyspy Owcze",
    # Ameryka Południowa
    "Brazil": "Brazylia",
    "Argentina": "Argentyna",
    "Colombia": "Kolumbia",
    "Uruguay": "Urugwaj",
    "Ecuador": "Ekwador",
    "Venezuela": "Wenezuela",
    "Paraguay": "Paragwaj",
    "Bolivia": "Boliwia",
    "Peru": "Peru",
    "Chile": "Chile",
    # Ameryka Północna i Środkowa
    "United States": "USA",
    "USA": "USA",
    "Mexico": "Meksyk",
    "Canada": "Kanada",
    "Panama": "Panama",
    "Jamaica": "Jamajka",
    "Honduras": "Honduras",
    "El Salvador": "Salwador",
    "Costa Rica": "Kostaryka",
    "Trinidad and Tobago": "Trynidad i Tobago",
    "Guatemala": "Gwatemala",
    "Cuba": "Kuba",
    "Haiti": "Haiti",
    # Azja
    "Japan": "Japonia",
    "South Korea": "Korea Południowa",
    "Korea Republic": "Korea Południowa",
    "Australia": "Australia",
    "Iran": "Iran",
    "Saudi Arabia": "Arabia Saudyjska",
    "Qatar": "Katar",
    "Iraq": "Irak",
    "Jordan": "Jordania",
    "Uzbekistan": "Uzbekistan",
    "China PR": "Chiny",
    "China": "Chiny",
    "Indonesia": "Indonezja",
    "Bahrain": "Bahrajn",
    "Oman": "Oman",
    "United Arab Emirates": "ZEA",
    "UAE": "ZEA",
    "Palestine": "Palestyna",
    "Thailand": "Tajlandia",
    "Vietnam": "Wietnam",
    "Malaysia": "Malezja",
    "Philippines": "Filipiny",
    "Syria": "Syria",
    "Lebanon": "Liban",
    "Kuwait": "Kuwejt",
    "India": "Indie",
    "Kyrgyzstan": "Kirgistan",
    "Tajikistan": "Tadżykistan",
    "Myanmar": "Mjanma",
    "Bangladesh": "Bangladesz",
    "Nepal": "Nepal",
    "Sri Lanka": "Sri Lanka",
    # Afryka
    "Morocco": "Maroko",
    "Senegal": "Senegal",
    "Nigeria": "Nigeria",
    "Egypt": "Egipt",
    "Cameroon": "Kamerun",
    "Ivory Coast": "Wybrzeże Kości Słoniowej",
    "Côte d'Ivoire": "Wybrzeże Kości Słoniowej",
    "Ghana": "Ghana",
    "Tunisia": "Tunezja",
    "Algeria": "Algieria",
    "South Africa": "RPA",
    "Tanzania": "Tanzania",
    "Congo DR": "DR Kongo",
    "DR Congo": "DR Kongo",
    "Mali": "Mali",
    "Burkina Faso": "Burkina Faso",
    "Mozambique": "Mozambik",
    "Zimbabwe": "Zimbabwe",
    "Zambia": "Zambia",
    "Uganda": "Uganda",
    "Kenya": "Kenia",
    "Ethiopia": "Etiopia",
    "Angola": "Angola",
    "Gabon": "Gabon",
    "Benin": "Benin",
    "Cape Verde": "Zielony Przylądek",
    "Guinea": "Gwinea",
    "Equatorial Guinea": "Gwinea Równikowa",
    "Gambia": "Gambia",
    "Libya": "Libia",
    "Sudan": "Sudan",
    "Comoros": "Komory",
    "Madagascar": "Madagaskar",
    "Rwanda": "Rwanda",
    # Oceania
    "New Zealand": "Nowa Zelandia",
    "Fiji": "Fidżi",
    "Papua New Guinea": "Papua Nowa Gwinea",
}


def translate(name: str) -> str:
    return POLISH.get(name, name)
